using ExamSys.Database;
using ExamSys.Database.dbEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExamSys.Database.Seeds
{
    public class seed_Courses
    {
        public static void seed(ExamDB context)
        {

            IList<Courses> Courses = new List<Courses>()
            {
                new Courses{id=1,Code="CS201",CH=2,Name="Introduction to computers",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=2,Code="CS202",CH=2,Name="Fundamentals of C Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                /*
                new Courses{id=1,Code="ACC311",CH=2,Name="Fundamentals of Auditing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=2,Code="ACC501",CH=2,Name="Business Finance",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=3,Code="BIF731",CH=2,Name="Advanced Bioinformatics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=4,Code="BIF732",CH=2,Name="Advanced Computing Approaches",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=5,Code="BIF733",CH=2,Name="Bioinformatics I (Essentials of Genome Informatics)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=6,Code="BIO201",CH=2,Name="Cell Biology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=7,Code="BIO202",CH=2,Name="Biochemistry-I",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=8,Code="BIO301",CH=2,Name="Essentials of Genetics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=9,Code="BIO302",CH=2,Name="Molecular Biology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=10,Code="BIO732",CH=2,Name="Gene Manipulation and Genetic Engineering",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=11,Code="BNK601",CH=2,Name="Banking Laws & Practices",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=12,Code="BNK603",CH=2,Name="Consumer Banking",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=13,Code="BT731",CH=2,Name="Modern Biotechnology: Principles & Applications",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=14,Code="BT733",CH=2,Name="Bioethics, Biosecurity and Biosafety",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=15,Code="CS101",CH=2,Name="Introduction to Computing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=16,Code="CS201",CH=2,Name="Introduction to Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=17,Code="CS206",CH=2,Name="Introduction to Network Design & Analysis",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=18,Code="CS301",CH=2,Name="Data Structures",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=19,Code="CS302",CH=2,Name="Digital Logic Design",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=20,Code="CS304",CH=2,Name="Object Oriented Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=21,Code="CS311",CH=2,Name="Introduction to Web Services Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=22,Code="CS312",CH=2,Name="Database Modeling and Design",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=23,Code="CS401",CH=2,Name="Computer Architecture and Assembly Language Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=24,Code="CS402",CH=2,Name="Theory of Automata",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=25,Code="CS403",CH=2,Name="Database Management Systems",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=26,Code="CS408",CH=2,Name="Human Computer Interaction",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=27,Code="CS410",CH=2,Name="Visual Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=28,Code="CS411",CH=2,Name="Visual Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=29,Code="CS501",CH=2,Name="Advance Computer Architecture",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=30,Code="CS502",CH=2,Name="Fundamentals of Algorithms",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=31,Code="CS504",CH=2,Name="Software Engineering - I",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=32,Code="CS506",CH=2,Name="Web Design and Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=33,Code="CS507",CH=2,Name="Information Systems",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=34,Code="CS508",CH=2,Name="Modern Programming Languages",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=35,Code="CS601",CH=2,Name="Data Communication",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=36,Code="CS602",CH=2,Name="Computer Graphics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=37,Code="CS604",CH=2,Name="Operating Systems",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=38,Code="CS605",CH=2,Name="Software EngineeringII",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=39,Code="CS606",CH=2,Name="Compiler Construction",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=40,Code="CS607",CH=2,Name="Artificial Intelligence",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=41,Code="CS609",CH=2,Name="System Programming",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=42,Code="CS610",CH=2,Name="Computer Network",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=43,Code="CS614",CH=2,Name="Data Warehousing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=44,Code="CS615",CH=2,Name="Software Project Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=45,Code="CS701",CH=2,Name="Theory of Computation",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=46,Code="CS702",CH=2,Name="Advanced Algorithms Analysis and Design",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=47,Code="CS703",CH=2,Name="Advanced Operating Systems",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=48,Code="CS704",CH=2,Name="Advanced Computer Architecture-II",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=49,Code="CS706",CH=2,Name="Software Quality Assurance",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=50,Code="CS707",CH=2,Name="Network Security",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=51,Code="CS708",CH=2,Name="Software Requirement Engineering",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=52,Code="CS709",CH=2,Name="Formal Methods for Software Engineering",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=53,Code="CS710",CH=2,Name="Mobile and Pervasive Computing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=54,Code="CS711",CH=2,Name="Software Design",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=55,Code="CS712",CH=2,Name="Distributed DBMS",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=56,Code="CS713",CH=2,Name="Object Oriented DBMS",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=57,Code="CS716",CH=2,Name="Advanced Computer Networks",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=58,Code="CS718",CH=2,Name="Wireless Networks",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=59,Code="CS721",CH=2,Name="Network Performance Evaluation",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=60,Code="CS723",CH=2,Name="Probability and Stochastic Processes",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=61,Code="CS724",CH=2,Name="Software Process Improvement",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=62,Code="CS726",CH=2,Name="Information Retrieval Techniques",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=63,Code="ECO401",CH=2,Name="Economics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=64,Code="ECO402",CH=2,Name="Microeconomics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=65,Code="ECO403",CH=2,Name="Macroeconomics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=66,Code="ECO404",CH=2,Name="Managerial Economics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=67,Code="ECO501",CH=2,Name="Development Economics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=68,Code="ECO601",CH=2,Name="Business Econometrics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=69,Code="EDU101",CH=2,Name="Foundations of Education",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=70,Code="EDU201",CH=2,Name="Learning Theories",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=71,Code="EDU301",CH=2,Name="General Methods of Teaching",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=72,Code="EDU303",CH=2,Name="Child Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=73,Code="EDU304",CH=2,Name="Introduction to Guidance and Counseling",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=74,Code="EDU305",CH=2,Name="Classroom Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=75,Code="EDU402",CH=2,Name="Curriculum Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=76,Code="EDU405",CH=2,Name="Classroom Assessment",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=77,Code="EDU406",CH=2,Name="Critical Thinking and reflective Practice",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=78,Code="EDU410",CH=2,Name="Teaching of Literacy Skills",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=79,Code="EDU411",CH=2,Name="Teaching of Urdu",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=80,Code="EDU501",CH=2,Name="School, Community and Teacher",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=81,Code="EDU505",CH=2,Name="Education Development in Pakistan",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=82,Code="EDU512",CH=2,Name="Teaching of Islamic Studies",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=83,Code="EDU515",CH=2,Name="Teaching of Geography",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=84,Code="EDU516",CH=2,Name="Teaching of English",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=85,Code="EDU601",CH=2,Name="Philosophy of Education",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=86,Code="EDU602",CH=2,Name="Educational Leadership and Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=87,Code="EDU603",CH=2,Name="Educational Governance Policy and Practice",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=88,Code="EDU654",CH=2,Name="Addressing problems of learning through technology and pedagogy",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=89,Code="ENG001",CH=2,Name="Elementary English",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=90,Code="ENG101",CH=2,Name="English Comprehension",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=91,Code="ENG201",CH=2,Name="Business and Technical English Writing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=92,Code="ENG301",CH=2,Name="Business Communication",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=93,Code="ETH202",CH=2,Name="Ethics (for Non-Muslims)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=94,Code="FIN611",CH=2,Name="Advanced Financial Accounting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=95,Code="FIN621",CH=2,Name="Financial Statement Analysis",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=96,Code="FIN622",CH=2,Name="Corporate Finance",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=97,Code="FIN623",CH=2,Name="Taxation Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=98,Code="FIN625",CH=2,Name="Credit & Risk Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=99,Code="FIN630",CH=2,Name="Investment Analysis & Portfolio Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=100,Code="GSC101",CH=2,Name="General Science",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=101,Code="GSC201",CH=2,Name="Teaching of General Science",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=102,Code="HRM617",CH=2,Name="Training and Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=103,Code="HRM624",CH=2,Name="Conflict Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=104,Code="HRM627",CH=2,Name="Human Resource Development",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=105,Code="HRM713",CH=2,Name="Performance Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=106,Code="ISL201",CH=2,Name="Islamic Studies",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=107,Code="IT430",CH=2,Name="E-Commerce",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=108,Code="MCD401",CH=2,Name="Camera basics, principles and practices",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=109,Code="MCD402",CH=2,Name="Lighting for TV Production",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=110,Code="MCD403",CH=2,Name="Music Production",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=111,Code="MCD404",CH=2,Name="Audio-Visual Editing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=112,Code="MCD501",CH=2,Name="TV Direction",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=113,Code="MCD502",CH=2,Name="Script Writing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=114,Code="MCD503",CH=2,Name="TV News and Current Affairs",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=115,Code="MCD504",CH=2,Name="Acting and Performance",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=116,Code="MCM101",CH=2,Name="Introduction to Mass Communication",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=117,Code="MCM301",CH=2,Name="Communication skills",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=118,Code="MCM304",CH=2,Name="Mass Media in Pakistan",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=119,Code="MCM310",CH=2,Name="Journalistic Writing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=120,Code="MCM311",CH=2,Name="Reporting and Sub-Editing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=121,Code="MCM401",CH=2,Name="Fundamentals of Public Relations",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=122,Code="MCM404",CH=2,Name="Globalization of Media",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=123,Code="MCM411",CH=2,Name="Introduction to Broadcasting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=124,Code="MCM501",CH=2,Name="Advertising for Print and Electronic Media",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=125,Code="MCM511",CH=2,Name="Theories of Communication",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=126,Code="MCM514",CH=2,Name="Feature & Column Writing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=127,Code="MCM515",CH=2,Name="Radio News Reporting & Production",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=128,Code="MCM516",CH=2,Name="TV News Reporting & Production",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=129,Code="MCM604",CH=2,Name="International Communication",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=130,Code="MCM610",CH=2,Name="Mass Communication Law & Ethics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=131,Code="MGMT611",CH=2,Name="Human Relations (alt. CH=2,Name=HRM611)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=132,Code="MGMT614",CH=2,Name="Supply Chain Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=133,Code="MGMT622",CH=2,Name="Management Skills",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=134,Code="MGMT623",CH=2,Name="Leadership & Team Management - MGMT623 (alt. CH=2,Name=HRM623)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=135,Code="MGMT625",CH=2,Name="Change Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=136,Code="MGMT627",CH=2,Name="Project Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=137,Code="MGMT628",CH=2,Name="Organizational Development (alt. CH=2,Name=HRM628)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=138,Code="MGMT629",CH=2,Name="Crisis Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=139,Code="MGMT630",CH=2,Name="Knowledge Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=140,Code="MGMT727",CH=2,Name="Project Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=141,Code="MGT101",CH=2,Name="Financial Accounting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=142,Code="MGT111",CH=2,Name="Introduction to Public Administration",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=143,Code="MGT201",CH=2,Name="Financial Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=144,Code="MGT211",CH=2,Name="Introduction To Business",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=145,Code="MGT301",CH=2,Name="Principles of Marketing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=146,Code="MGT401",CH=2,Name="Financial Accounting II",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=147,Code="MGT402",CH=2,Name="Cost & Management Accounting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=148,Code="MGT404",CH=2,Name="Managerial Accounting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=149,Code="MGT411",CH=2,Name="Money & Banking",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=150,Code="MGT501",CH=2,Name="Human Resource Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=151,Code="MGT502",CH=2,Name="Organizational Behaviour",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=152,Code="MGT503",CH=2,Name="Principles of Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=153,Code="MGT504",CH=2,Name="Organization Theory & Design",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=154,Code="MGT510",CH=2,Name="Total Quality Management (alt. CH=2,Name=MGMT510)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=155,Code="MGT520",CH=2,Name="International Business",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=156,Code="MGT601",CH=2,Name="SME Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=157,Code="MGT602",CH=2,Name="Entrepreneurship",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=158,Code="MGT603",CH=2,Name="Strategic Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=159,Code="MGT604",CH=2,Name="Management of Financial Institutions (alt. CH=2,Name=BNK604)",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=160,Code="MGT610",CH=2,Name="Business Ethics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=161,Code="MGT611",CH=2,Name="Business & Labor Law",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=162,Code="MGT612",CH=2,Name="Corporate Law",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=163,Code="MGT613",CH=2,Name="Production / Operations Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=164,Code="MGT621",CH=2,Name="Administrative Law and Accountability",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=165,Code="MGT705",CH=2,Name="Advanced Cost and Management Accounting",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=166,Code="MKT501",CH=2,Name="Marketing Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=167,Code="MKT530",CH=2,Name="Consumer Behaviour",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=168,Code="MKT603",CH=2,Name="Strategic Marketing Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=169,Code="MKT610",CH=2,Name="Customer Relationship Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=170,Code="MKT611",CH=2,Name="Marketing Research",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=171,Code="MKT621",CH=2,Name="Advertising & Promotion",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=172,Code="MKT624",CH=2,Name="Brand Management",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=173,Code="MKT625",CH=2,Name="Services Marketing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=174,Code="MKT630",CH=2,Name="International Marketing",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=175,Code="MTH001",CH=2,Name="Elementary Mathematics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=176,Code="MTH100",CH=2,Name="General Mathematics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=177,Code="MTH101",CH=2,Name="Calculus And Analytical Geometry",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=178,Code="MTH201",CH=2,Name="Multivariable Calculus",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=179,Code="MTH202",CH=2,Name="Discrete Mathematics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=180,Code="MTH301",CH=2,Name="Calculus II",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=181,Code="MTH302",CH=2,Name="Business Mathematics & Statistics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=182,Code="MTH303",CH=2,Name="Mathematical Methods",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=183,Code="MTH401",CH=2,Name="Differential Equations",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=184,Code="MTH501",CH=2,Name="Linear Algebra",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=185,Code="MTH601",CH=2,Name="Operations Research",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=186,Code="MTH603",CH=2,Name="Numerical Analysis",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=187,Code="PAK301",CH=2,Name="Pakistan Studies",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=188,Code="PAK302",CH=2,Name="Pakistan Studies",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=189,Code="PHY101",CH=2,Name="Physics",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=190,Code="PHY301",CH=2,Name="Circuit Theory",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=191,Code="PSC201",CH=2,Name="International Relations",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=192,Code="PSC401",CH=2,Name="Public International Law",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=193,Code="PSY101",CH=2,Name="Introduction to Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=194,Code="PSY401",CH=2,Name="Clinical Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=195,Code="PSY403",CH=2,Name="Social Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=196,Code="PSY404",CH=2,Name="Abnormal Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=197,Code="PSY405",CH=2,Name="rPersonality Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=198,Code="PSY406",CH=2,Name="Educational Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=199,Code="PSY407",CH=2,Name="Sport Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=200,Code="PSY408",CH=2,Name="Health Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=201,Code="PSY409",CH=2,Name="Positive Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=202,Code="PSY502",CH=2,Name="History & Systems of Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=203,Code="PSY504",CH=2,Name="Cognitive Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=204,Code="PSY510",CH=2,Name="Organizational Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=205,Code="PSY511",CH=2,Name="Environmental Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=206,Code="PSY512",CH=2,Name="Gender Issues in Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=207,Code="PSY513",CH=2,Name="Forensic Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=208,Code="PSY514",CH=2,Name="Consumer Psychology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=209,Code="PSY610",CH=2,Name="Neurological Bases of Behavior",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=210,Code="PSY631",CH=2,Name="Psychological Testing & Measurements",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=211,Code="PSY632",CH=2,Name="Theory & Practice of Counseling",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=212,Code="SOC101",CH=2,Name="Introduction to Sociology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=213,Code="SOC401",CH=2,Name="Cultural Anthropology",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=214,Code="STA301",CH=2,Name="Statistics and Probability",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=215,Code="STA630",CH=2,Name="Research Methods",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=216,Code="STA730",CH=2,Name="Advance Research Methods",created_at = DateTime.Now,edited_at = DateTime.Now },
                new Courses{id=217,Code="URD101",CH=2,Name="Urdu",created_at = DateTime.Now,edited_at = DateTime.Now },
            */
            };

            foreach (var item in Courses)
                context.Courses.Add(item);

            context.SaveChanges();
        }
    }
}
